const playlist = [
    { title: "Вам 18 лет", url: "mutsuraev_music/muts1.webm" },
    { title: "Город Грозный", url: "mutsuraev_music/muts2.webm" },
    { title: "Грозный, ты держал врага", url: "mutsuraev_music/muts3.webm" },
    { title: "Дождь и Я", url: "mutsuraev_music/muts4.webm" },
    { title: "Если духом ты слаб", url: "mutsuraev_music/muts5.webm" },
    { title: "Жизнь прошла Remix", url: "mutsuraev_music/muts6.webm" },
    { title: "Золотых Монет", url: "mutsuraev_music/muts7.webm" },
    { title: "Кавказ - Моя отчизна", url: "mutsuraev_music/muts8.webm" },
    { title: "Когда мне было ровно пять", url: "mutsuraev_music/muts9.webm" },
    { title: "Милые Зеленые Глаза", url: "mutsuraev_music/muts10.webm" },
    { title: "Не зови ты меня не зови", url: "mutsuraev_music/muts11.webm" },
    { title: "Нежная Походка + SLOWED + REVERB", url: "mutsuraev_music/muts12.webm" },
    { title: "НОВИНКА ТИМУРА МУЦУРАЕВА! ПОСЛУШАЙТЕ.", url: "mutsuraev_music/muts13.webm" },
    { title: "О милость дарующий (отрывок)", url: "mutsuraev_music/muts14.webm" },
    { title: "О, Аллах", url: "mutsuraev_music/muts15.webm" },
    { title: "Погасли свечи", url: "mutsuraev_music/muts16.webm" },
    { title: "Погасли свечи (Версия 2)", url: "mutsuraev_music/muts17.webm" },
    { title: "Сталин", url: "mutsuraev_music/muts18.webm" },
    { title: "Твоя Нежная Походка - Оригинал", url: "mutsuraev_music/muts19.webm" },
    { title: "Тимур Муцураев - Байсангур Беноевский", url: "mutsuraev_music/muts20.webm" },
    { title: "Тимур Муцураев - Бамут", url: "mutsuraev_music/muts21.webm" },
    { title: "Тимур Муцураев - Ветер Свободы", url: "mutsuraev_music/muts22.webm" },
    { title: "Тимур Муцураев - Король и Пастух", url: "mutsuraev_music/muts23.webm" },
    { title: "Тимур Муцураев - Мы вернемся, Грозный", url: "mutsuraev_music/muts24.webm" },
    { title: "Тимур Муцураев - Нет дороги назад", url: "mutsuraev_music/muts25.webm" },
    { title: "Тимур Муцураев - НИКОГДА НЕ ПАДАЙ ДУХОМ", url: "mutsuraev_music/muts26.webm" },
    { title: "Тимур Муцураев - НОЧИ ОГНЯ", url: "mutsuraev_music/muts27.webm" },
    { title: "Тимур Муцураев - О милость дарующий (другая версия)", url: "mutsuraev_music/muts28.webm" },
    { title: "Тимур Муцураев - СВОБОДЫ ВЕТЕР", url: "mutsuraev_music/muts29.webm" },
    { title: "Тимур Муцураев - ЧЕЧЕНЕЦ Я", url: "mutsuraev_music/muts30.webm" },
    { title: "Тимур Муцураев - ЧЕЧЕНСКИЙ СПЕЦНАЗ", url: "mutsuraev_music/muts31.webm" },
    { title: "Тимур Муцураев - Вечно живи Чечня", url: "mutsuraev_music/muts32.webm" },
    { title: "Тимур Муцураев - Грозный Ты Держал Врага", url: "mutsuraev_music/muts33.webm" },
    { title: "Тимур Муцураев - Добро пожаловать в Ад !!!", url: "mutsuraev_music/muts34.webm" },
    { title: "Тимур Муцураев - Душа подступит к горлу", url: "mutsuraev_music/muts35.webm" },
    { title: "Тимур Муцураев - Жизни путь лишь один", url: "mutsuraev_music/muts36.webm" },
    { title: "Тимур Муцураев - Жизнь Прошла 2007 Ночь своим молчанием", url: "mutsuraev_music/muts37.webm" },
    { title: "Тимур Муцураев - Жизнь суета", url: "mutsuraev_music/muts38.webm" },
    { title: "Тимур Муцураев - Има твоё Грозный", url: "mutsuraev_music/muts39.webm" },
    { title: "Тимур Муцураев - Мама приезжай и меня забери", url: "mutsuraev_music/muts40.webm" },
    { title: "Тимур Муцураев - МОЙ ГРОЗНЫЙ", url: "mutsuraev_music/muts41.webm" },
    { title: "Тимур Муцураев - Муса пророк и Грешник", url: "mutsuraev_music/muts42.webm" },
    { title: "Тимур Муцураев - Мы вернемся в ГРОЗНЫЙ", url: "mutsuraev_music/muts43.webm" },
    { title: "Я мусульманин", url: "mutsuraev_music/muts44.webm" },
    { title: "Тимур Муцураев - Добро пожаловать в Ад !!! (Вариант)", url: "mutsuraev_music/muts45.webm" }
];
